saltstack/salt-contrib

grains/ec2_tags.py

This does alter the order of preferred configuration to be a bit more overridable, namely environment variables or salt-minion configuration override what is specified in the file itself, providing a default. Before the locally specified configuration was the top priority, preventing any ability to override them.
This also fixes running the grain outside of Salt to test by checking for dunder dict presence before accessing them.

Syntax error in ec2_tags gain, big cleanup and merge in ec2_tag_roles functionality

---

states/iis.py

The following state fails when the vdir already exists because the straight concatenation of the app+name results in double slashes which are not found when checking for an existing vdir, e.g. it is looking for "Default Web Site//test" when the real id is "Default Web Site/test".
test.vdir:
iis.vdir_present:
- name: /test
- app: Default Web Site/
- settings:
physicalPath: C:\inetpub\wwwroot\test
Here is the debug output from the minion:
2015-03-02 10:46:13,365 [salt.template    ][DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\test.sls:
test.vdir:
iis.vdir_present:
- name: /test
- app: Default Web Site/
2015-03-02 10:46:13,365 [salt.loaded.int.render.yaml][DEBUG   ] Results of YAML rendering: 
OrderedDict([('test.vdir', OrderedDict([('iis.vdir_present', …

Fix detection of existing non-root vdir

---

grains/ec2_tags.py

On instances where the IAM role is configured with access to describe ec2 instance tags, recent versions of boto can automatically get the role credentials from the instance metadata and use them to fetch tags.

Rely on boto to get IAM role from instance metadata

---

modules/iis.py

Configuring `IIS` had a weird behavior of not being able to find `appcmd.exe`. This was happening due to excessive quoting and splitting of the command line. 
In order to avoid these issues, use an explicit `list` of arguments instead of plain `str` to `run` `appcmd.exe`.

Fixes issue #124

---

grains/shortname.py

Today, I ran into the `host:` grain returning a shortname, but one that I wasn't expecting.
The system in question has an IP address that is  not RFC1918, and I don't control either forward or reverse DNS for it.  So it returns some value from the ISP that's totally not what I want.
This grain does, regardless of the IP address of the system, via the `uname()` system call.

Adding a simple grain to emulate hostname -s in python.

---

grains/ec2_info.py

When using the ec2_pillar, the grain that it looks for
to identify the instance-id of an aws node is grains['instance-id'].
The ec2_info grain doesn't provide this, and as far
as I can tell, neither does anything else in the salt
ecosystem at this point.
In order to provide that, this commit adds another public function to
the ec2_info code that provides the 'instance-id' gtrain that the
ec2_pillar expects when it's configured with 'use_grain=True'.
The code in ec2_pillar that this supports is at:
https://github.com/saltstack/salt/blob/561d7b72bb8bb0d5fa5c4395db12425f27c26c1a/salt/pillar/ec2_pillar.py#L73-L91

Record the ec2 instance-id as a top-level grain

---

grains/ec2_info.py

Public keys are little different than other metadata - here's the AWS documentation on how to retrieve the public keys - http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
This example gets the list of available public keys.
```bash
$ curl http://169.254.169.254/latest/meta-data/public-keys/
0=my-public-key
```
This example shows the formats in which public key 0 is available.
```bash
$ curl http://169.254.169.254/latest/meta-data/public-keys/0
openssh-key
```
This example gets public key 0 (in the OpenSSH key format).
```bash
$ curl http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key
ssh-rsa MIICiTCCAfICCQD6m7oRw0uXOjANBgkqhkiG9w0BAQUFADCBiDELMAkGA1UEBhMC
VVMxCzAJBgNVBAgTAldBMRAwDgYDVQQHEwdTZWF0dGxlMQ8wDQYDVQQKEwZBbWF6 …
```

#123: Fixed the ec2:public_key grain.  

---

returners/tcp_returner.py

This is a TCP socket returner which sends the state execution events to a TCP listener like Splunk.
The data is send in json format and could be used for reporting and creating dashboards in Splunk.

TCP socket returner which returns state execution events

---

modules/iis.py

Fixes the [reported issue](https://github.com/saltstack/salt-contrib/issues/138) with *get_data_from_pfx*, *cert_import_pfx*, and *pfx_present* when importing or checking the permissions on a PFX encrypted with an empty password.
The state file used to test the modification, using one certificate with an empty password, and one with a password defined:
```
import-cert-mvcforum-test1:
iis.pfx_present:
- name: 'C:\Company\Certs\mvcforum.pfx'
import-cert-mvcforum-test2:
iis.pfx_present:
- name: 'C:\Company\Certs\mvcforum.pfx'
- password: ''
import-cert-mojoportal-test1:
iis.pfx_present:
- name: 'C:\Company\Certs\mojoportal.pfx'
- password: 'Vertigo'
```
Results:
```
m03@salt01:/salt/state/web/windows/iis$ sudo salt 'win2012r2' state.sls web.windows.iis.cert_test
win2012r2:
----------
ID: …
```

Fixed empty password issue with PFX import in IIS

---

modules/win_msloop.py
states/win_msloop.py

**Summary**
* Added execution and state modules to manage Microsoft Loopback Adapters. 
**Testing**
* Tested against Windows 2012r2, with devcon.exe version 6.3.9600.17029, running salt-minion 2015.5.8.

Add modules to manage Microsoft Loopback Adapters

---

renderers/jproperties.py

Sometimes pillar or grains data might need to come from Java properties. This simple wrapper adds rendering using the jproperties package from PyPI.

jproperties renderer

---

modules/flup_fcgi_client.py

PHP 5.3.3 returns a broken header, e.g. 
----
X-Powered-By: PHP/5.3.3
application/jsonrequest
Content-type: text/html
{"accepted conn":6660,"pool":"cloudcell","process manager":"dynamic","idle processes":56,"active processes":1,"total processes":57}
--
It now ignores it and carry on with the execution.

Error handling - Some PHP version have broken document type header

---

grains/vultr.py

This grain queries the metadata service provided by Vultr.
Not as many grains are currently supported as other service providers,
but it's better than nothing
```
root@vu001:~# salt-call -l quiet grains.get vultr
local:
----------
SUBID:
2829492
instance-id:
978a662e21763da5e3b7be7a0d892523
ipv6-addr:
ipv6-prefix:
local-ipv4:
mac:
56:00:00:16:c5:99
public-ipv4:
18.32.167.20
```

Add vultr metadata service grain

---

grains/ec2_info.py

This makes values returned for local_ipv4s with secondary IPs easier to work with.
`salt '*' grains.items --output=yaml`
before:
```
...
local_ipv4s: '10.0.0.117
10.0.0.114
10.0.0.115
10.0.0.116
10.0.0.118
10.0.0.119
10.0.0.120
10.0.0.121
10.0.0.122
10.0.0.123'
...
```
after:
```
...
local_ipv4s:
- 10.0.0.117
- 10.0.0.114
- 10.0.0.115
- 10.0.0.116
- 10.0.0.118
- 10.0.0.119
- 10.0.0.120
- 10.0.0.121
- 10.0.0.122
- 10.0.0.123
...
```

convert response data containing newlines to lists

---

grains/ec2_info.py

On cloud hosts such as Vultr the cloud-init identity document returned is empty.

Error handling for empty ec2 additional info

---

modules/octopus_tentacle.py
states/octopus_tentacle.py
tests/unit/modules/octopus_tentacle_test.py

* PLEASE NOTE: I was unsure if this should be contributed to salt or salt-contrib. I can submit a new pull to salt if that makes more sense.
* Adds execution and state modules for [Octopus Deploy](https://octopus.com/) Tentacle client on Windows minions.
* Adds some execution module unit tests for the above.
* None
* Ability to manage Octopus Deploy Tentacle client on Windows minions did not previously exist.
* Adds execution and state modules for Octopus Deploy Tentacle client on Windows minions.
* Adds some execution module unit tests for the above.
Yes

Add OctopusDeploy client modules for Windows

---

grains/hw_raid.py

Fails for me on old machines Dell 1950/2950 running Debian Wheezy 2950. Try/except to find driver.

try except for _kmod_info(pci_data['driver'])

---

grains/ec2_info.py
grains/ec2_tags.py

This patch handles the python 3 httplib to http.client change. In addition, decode responses from http client from bytes to unicode strings.

Python 3 compatibility for the ec2_info grain

---

grains/hw_raid.py

Some RAID devices are appeared as "Serial Attached SCSI" in `lspci` output like The [FusionMPT SAS2](https://hwraid.le-vert.net/wiki/LSIFusionMPTSAS2) is a low-end card from LSI.
An example for the output:
```
03:00.0 Serial Attached SCSI controller: LSI Logic / Symbios Logic SAS2004 PCI-Express Fusion-MPT SAS-2 [Spitfire] (rev 03)
```

Add support for RAID via Serial Attached SCSI.

---

modules/cat.py

The `cat.py` module is usable by Jinja. Its purpose is to include lines from another file, or from a set of files in a directory (with optional recursing into subdirectories).
This is a workaround I suggested to those affected by https://github.com/saltstack/salt/issues/22063

Added cat.py, a workaround for Salt Issue #22063

---

grains/gce.py

Other than the long path, this passes both `pylint` and `flake8`.

Move closer to PEP8 and Salt style

---

grains/ec2_info.py

ec2_info function _get_ec2_user_data  return as a binary object and needs to be decoded.  This decode is used in other ec2_info functions

ec2_info function _get_ec2_user_data does not return data
